title: Truth is between you and me
email: thinner_01sullen@icloud.com
description: >-
  Life is meaningless unless got to make a sense
baseurl: "" # 网站的子路径，例如 /blog
url: "" # 网站的基础 URL，例如 http://amosqiang.github.io
twitter_username: amosqiang
github_username: amosqiang

# Staticman 配置 (请替换你的 GitHub 用户名)
staticman:
  api: "https://api.staticman.net/v3/entry"
  username: "amosqiang" # 你的 GitHub 用户名
  repo: "amosqiang.github.io" # 你的 GitHub 仓库名

# 构建设置
theme: minima
plugins:
  - jekyll-feed

collections:
  posts:
    output: true
    sort_by: date
    order: desc

# 排除处理的文件和目录
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# exclude:
#  - .sass-cache/
#  - .jekyll-cache/
#  - gemfiles/
#  - Gemfile
#  - Gemfile.lock
#  - node_modules/
#  - vendor/bundle/
#  - vendor/cache/
#  - vendor/gems/
#  - vendor/ruby/