title: Truth is between you and me
email: thinner_01sullen@icloud.com
description: >-
  Zen
baseurl: "" # 网站的子路径，例如 /blog
url: "" # 网站的基础 URL，例如 http://amosqiang.github.io
twitter_username: amosqiang
github_username: amosqiang
timezone: America/Anchorage # <--- 添加的阿拉斯加时区

# 构建设置
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

collections:
  posts:
    output: true
    sort_by: date
    order: desc

# 排除处理的文件和目录
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - requirements.txt
  - sync_to_x.py
  - last_post_guid.txt
  - deploy.sh
  - vendor/bundle/   # 通常也建议排除
  - node_modules/    # 如果使用 npm
  - _site/           # Jekyll 通常默认排除，但明确写上无害
  - .github/         # 通常也排除 Actions 配置